### PR TITLE
Cast hDAO balance from Conseil as integer

### LINKED ISSUE #70: Some mints are incorrectly not showing in /featured feed
This is caused because hdaoMap hdao balance values are sometimes strings.
This causes minterBaseScore to become a string, and the incorrect total score means the item doesn't get included in /featured.

```
GET http://localhost:3001/featured?counter=0&max_time=1620570720000
//add console.log to conseil.js:artisticUniverse L1208

o.minter tz1KyMb5TpWm3ED8WUbt5xDHVBkDhiQbKk1W
minterScore 0.35178571428571426 number
minterhDAO 90009890 string <<<<<<<<<<
minterBaseScore 900098902473.05357142857131664193.446428567 string <<<<<<<<<<
thresholdHdao 7030 number
replacementScore 0.35178571428571426 number
backendConf.tzktScorehDAOMultiplier 1 number
```

### PR DESCRIPTION
**Pull request by skenaja**
Fixes #70

### CODE REVIEW

**Comment by skenaja** [comment]
@veqtor - for review.

**Comment by crzypatchwork** [comment]
it does solve the bug on the feed but the /tz route is damaged ;/

**Comment by crzypatchwork** [comment]
this objkt seems to go into the feed which also doesn't make any sense 71873

**Comment by skenaja** [comment]
When they minted the first objkt, it looks like the tzkt profiles API was rate limiting, returning `http 429`. 
This triggered the "replacementScore" for their profile. This would have been enough to allow 1 objkt to appear.
They minted some more objkts just afterwards, this made 71873 no longer appear in `/featured` when I ran it, as they minted too many in a 3hr/1 week window.

Having tzkt profiles in the DB would eliminate this issue.

```
o.minter tz1aUV4yVo97Xw5PDjzhdyq2BUbzwoymyhGF
minterMintsWeek 8 number
minterMints3hExp 1 number
minterFreeObjkts 5.35 number
minterScore 0.3821428571428571 number
minterhDAO 0 number
minterBaseScore 2757.160714285714 number
divisor 3.6500000000000004 number
thresholdHdao 7215 number
replacementScore 0.3821428571428571 number 
backendConf.tzktScorehDAOMultiplier 1 number
backendConf.filterWeeklyFreeObjkts 14 number
minterBaseScore/divisor 755.3864970645792
minterBaseScore/divisor greater than thresholdHdao? false

```

**Comment by veqtor** [comment]
> it does solve the bug on the feed partially. objkt 71873 seems to go into the feed which doesn't make any sense due the issuer being an account without tzkt registry nor hDAOs

We need redis, how do you want to store the credentials?

**Pull request merged**
