### PR TITLE
Add new feed type - hDAO thresholded

### PR DESCRIPTION
**Pull request by veqtor**
We still struggle with copyminters and spammers, this introduces a new feed that has less of it and it is relative to the amount of mints within the last week, meaning bot-accounts that mint 100+ mints per week also will not show up.

Still, this change is quite radical, so I've also retained the old feed as /feed, which should be implemented in the UI, but this should ideally be the default feed.

We can decide later which we want as the default, but for now this new feed is under /featured

For now this threshold is: (User hDAO / (max(1, mints this week) )) > 1 hDAO (1_000_000 nat)

### CODE REVIEW

**Comment by veqtor** [comment]
Added a volatility dampening mechanism, with this merged Hic Et Nunc officially becomes a DeFI dapp.
We use pricing data from quipuswap to set threshold such that "being on feed" hDAO-balance is no more than 0.1 tez, no less than 0.0001 hDAO and no more than 1 hDAO, all counted as per-object minted the last week.

So say you have 140 hDAO, very common
You mint 7 objekt this last week, hDAO price is low, 20 hdao per tez, max limit will then be 1 hdao per objekt because of 1 hDAO limit so we need 7 hDAO to be shown on feed, we have 10 times that so we're good.

If hDAO price was super high, we would instead hit the 0.1 tez limit instead.

**Comment by skenaja** [comment]
Won't this be unfair to the genuine new artists who haven't sold yet? They would have even less of a chance for discovery on the homepage if the level of hDAO they hold is taken into account, as they'll have 0. Perhaps just a throttle so that no more than 1 or objkts per artist can be in the feed per 24 hours, or there could be a mechanism for verified artists (ie if they have [tzkt.io metadata populated](https://api.tzkt.io/v1/accounts/tz1fb6jz7rh4H7AojLShvhiXKaSNDyvkH7sM/metadata)) to be upboosted or given a few free hDAO.

**Comment by veqtor** [comment]
> Won't this be unfair to the genuine new artists who haven't sold yet? They would have even less of a chance for discovery on the homepage if the level of hDAO they hold is taken into account, as they'll have 0. Perhaps just a throttle so that no more than 1 or 2 objkts per artist can be in the feed per 24 hours, or there could be a mechanism for verified artists (ie if they have [tzkt.io metadata populated](https://api.tzkt.io/v1/accounts/tz1fb6jz7rh4H7AojLShvhiXKaSNDyvkH7sM/metadata)) to be upboosted or given a few free hDAO.

Indeed, a 24 hour grace period for those with tzkt Metadata could solve that problem, good idea

**Comment by skenaja** [comment]
BTW, aside from quipuswap it's also currently possible to acquire 1 hDAO for the cost of 0.026 XTZ (site+gas fees) by laundering an 1 XTZ artwork to yourself, and gaining the buyer/seller hDAO reward. This price is a rate of ~38 hdao/xtxz, the same as on quipuswap. This rate isn't going to change until the supply of hDAO from hic dries up.

**Comment by veqtor** [comment]
> BTW, aside from quipuswap it's also currently possible to acquire 1 hDAO for the cost of 0.026 XTZ (site+gas fees) by laundering an 1 XTZ artwork to yourself, and gaining the buyer/seller hDAO reward. This price is a rate of ~38 hdao/xtxz, the same as on quipuswap. This rate isn't going to change until the supply of hDAO from hic dries up.

Sure, but you loose a little bit in the process

**Comment by mathMakesArt** [comment]
> Sure, but you loose a little bit in the process

You do, but the amount lost will consistently approach (not exactly, due to fees) 0.025 XTZ per 1 hDAO gained, or 40 hDAO per 1 XTZ. So at least for the remainder of the hDAO reward period, some people will likely be "generating" hDAO whenever a high enough arbitrage opportunity is present on quipuswap.

**Comment by veqtor** [comment]
Now adjusted so everything is exactly as it is right now, only we have the ability to toggle this on and off in the UI

**Comment by veqtor** [comment]
I switched things around, main feed is now as it used to be but this introduces a new feed called "featured"

**Comment by andrevenancio** [comment]
+1 to this feature to be merged ASAP!

**Pull request merged**
