### PR TITLE
adding fake API call

### PR DESCRIPTION
**Pull request by andrevenancio**
Just as we spoke, here's a draft of an API method the frontend can call to get a collection.

Feel free to change it.

### CODE REVIEW

**Comment by veqtor** [comment]
What's the point of this, it's a fake call so you can begin work on something?

**Comment by andrevenancio** [comment]
It's not fake on my end. If the api exits I can plan my app logic around that api endpoint then at some point rafael will send the right data without the frontend changing

**Comment by veqtor** [comment]
Could you move this to new router?

**Comment by andrevenancio** [comment]
closing this as the galleries end up being implemented in a different way.

**Pull request closed without merging**
