### PR TITLE
Feature - add swagger docs

### PR DESCRIPTION
**Pull request by skenaja**
Add first draft of swagger docs. Only one of the APIs is fully documented, just to get some feedback for this PR.

The docs are generated using [swagger-autogen](https://github.com/davibaltar/swagger-autogen) based on comments added to each of the main endpoint methods. The generated file allows you to test the API with different parameters and view results.

chrome-capture

Implements #21

### CODE REVIEW

**Comment by crzypatchwork** [comment]
could you disable the swagger logo on the top? it's quite easily configurable swagger on express it seems

**Comment by skenaja** [comment]
Done. I also applied a pre-built monochrome theme to sort of match the site.

image

**Comment by skenaja** [comment]
This is probably good to go for a first pass. @crzypatchwork @veqtor I'd recommend merging it soonish so I don't have to keep resolving conflicts to keep up with the all the ongoing code changes in `index.js`.

**Comment by crzypatchwork** [comment]
I'll need to just verify some serverless compatibility for swagger

**Comment by veqtor** [comment]
Hi, we redid a lot of things, would you consider remaking this, would be very appreciated, sorry for the inconvenience

**Comment by skenaja** [comment]
Closing in favour of #64

**Pull request closed without merging**
