### PR TITLE
Extra collection details

### PR DESCRIPTION
**Pull request by anonymoussprocket**
Matching collection functionality to [T2/Gallon 1.1.16](https://github.com/Cryptonomic/T2/releases/tag/1.1.16b).

- increase resultset size to 20k
- show last price
- show last acquisition date
- show acquisition action
- sort collection by acquisition date

### CODE REVIEW

**Comment by veqtor** [comment]
Hi, I tested this, and I don't see anything that is different, what is changed exactly?

What would be accompanying changes to the UI to expose the features introduced by this PR?

I find no breaking changes anyway so LGTM

**Comment by veqtor** [comment]
Still conflicts in package.json :/

**Comment by veqtor** [comment]
Nice!

**Comment by veqtor** [comment]
Sorry about this becoming stale, is it still relevant, do you want to update?

**Comment by anonymoussprocket** [comment]
i'll resolve the conflicts

**Pull request merged**
